AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a Lambda function to rotate Snowflake credentials in AWS Secrets Manager"

Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref AWS::StackName
      Description: "AWS Secrets Manager Snowflake Rotation Lambda"
      Handler: lambda.handler
      Runtime: python3.12
      Role: !GetAtt Role.Arn
      Timeout: 30
      MemorySize: 128
      Code: ./lambda.py
      Layers:
        - !Ref Requirements

  Requirements:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-requirements"
      Content: ./target/requirements.zip
      CompatibleRuntimes:
        - python3.12

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AWS::StackName
      Description: "Role for AWS Secrets Manager Snowflake Rotation Lambda"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Runtime
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt LogGroup.Arn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                  - secretsmanager:UpdateSecretVersionStage
                  - secretsmanager:DescribeSecret
                Resource: "*"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}"
      RetentionInDays: 30

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Lambda
      Principal: secretsmanager.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

Outputs:
  Lambda:
    Description: Lambda ARN
    Value: !GetAtt Lambda.Arn

  Role:
    Description: Role ARN
    Value: !GetAtt Role.Arn
